name: Refresh Tokens

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout contents
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      
      - name: Cache pip modules
        id: cached-items
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
          
      - name: Install packages using pip
        if: steps.cached-items.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test Imports and Env Variables
        env:
          CLIENT_ID: ${{secrets.CLIENT_ID}}
          CLIENT_SECRET: ${{secrets.CLIENT_SECRET}}
          code: ${{secrets.CODE}}
          code_verifier: ${{secrets.CODE_VERIFIER}}
          refresh_token: ${{secrets.MAL_REFRESH_TOKEN}}
          PAT: ${{secrets.PAT}}
        run: |
          python workflowScripts/testImports.py

      # - name: Run script to refresh tokens
      #   env:
      #     CLIENT_ID: ${{secrets.CLIENT_ID}}
      #     CLIENT_SECRET: ${{secrets.CLIENT_SECRET}}
      #     code: ${{secrets.CODE}}
      #     code_verifier: ${{secrets.CODE_VERIFIER}}
      #     refresh_token: ${{secrets.REFRESH_TOKEN}}
      #     PAT: ${{secrets.PAT}}
      #   run: |
      #     python workflowScripts/accessTokens.py
