name: update DataBase

on: workflow_call

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout contents
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: install packages using pip
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute python script
        run: python updateDB.py
